[FEAT] 북마크화면 UI 구성
PLUB2022/PLUB-iOS pull request #161
Opened 2023-02-16 17:51 UTC by dlrjswns

## 📌 PR 요약

🌱 작업한 내용
- 내가 북마크한 모임글 보여주기 
- 북마크 조회관련 API 연동
- 차트 그리드 버튼에 따른 동작 구현

🌱 PR 포인트
- 북마크 등록/취소 API에서 9000번 상태코드 에러발생으로 기능이 제대로 동작하는지 확인 불가 
- 북마크 전체 조회 API에 대한 상태코드로는 success로 잘 내려오는듯

## 📮 관련 이슈
- Resolved: #160

2023-02-17 08:24 UTC, WhiteHyun requested changes
만약 테스트를 진행하셨다면 UI 오류가 발생한 것을 즉시 눈치채셨을 것이라 생각합니다. 그런데 테스트를 하지 않았던 이유가 무엇인지 궁금하네요.
다음에는 PR을 올리기전에 **검증**과 **테스트**를 반드시 **수행해주시기를 당부드립니다**.

2023-02-17 08:24 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/BookmarkViewModel.swift
> +    }
이거 따로 TODO 주석 작성 안하셔도 상관 없으신가요? 나중에 통신 에러 처리할 때 힘드실  것 같아서요

2023-02-17 08:24 UTC, WhiteHyun commented on PLUB/Sources/Models/Recruitment/Response/BookmarkAllResponse.swift
> +  let views: Int
views는 무엇일까요? 궁금하네요

2023-02-17 08:24 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/BookmarkViewModel.swift
> +        + "(data.time)"))
1. 요일은 이제 한글로 응답하므로 mapping은 필요하지 않아 보입니다.
2. data.time을 소괄호로 감싸신 이유가 무엇인지 궁금합니다. 해당 부분에 대해 테스트를 해보셨는지도 함께 고려해보시면 좋을 것 같습니다.

2023-02-17 08:24 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/BookmarkViewController.swift
> +class BookmarkHeaderView: UIView {
`BookmarkHeaderView`를 override되게끔 구현하신 이유가 궁금합니다.

2023-02-17 08:24 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/BookmarkViewController.swift
> +}
layout만 변경하시는 거라면 reloadData보다는 `invalidateLayout()`을 권장합니다.

```suggestion
  func didTappedInterestListChartButton() {
    selectedCategoryType = .chart
    interestListCollectionView.collectionViewLayout.invalidateLayout()
  }
  
  func didTappedInterestListGridButton() {
    selectedCategoryType = .grid
    interestListCollectionView.collectionViewLayout.invalidateLayout()
  }
}
```

2023-02-17 08:24 UTC, WhiteHyun commented on PLUB/Sources/Models/Recruitment/Response/BookmarkAllResponse.swift
> +}
Model에서 decoding할 때 서버로부터 값을 못 받으면 기본값을 설정해주는 게 맞는걸까요? 이렇게 한다면 서버 통신작업할 때 무조건 success가 뜨지는 않을지 염려스럽네요. 제가 걱정하는 것이 맞다면, 나중에 UI 처리에 대한 오류가 났을 때 어디에서 오류가 발생했는지 찾기 어려울 수 있습니다.
Model에서 해당 로직을 구현하는 것보다는 나중에 서버 로직을 작성한 부분에서 처리해주는 건 어떨까요?

2023-02-17 08:24 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/BookmarkViewController.swift
> +      UIBarButtonItem(image: UIImage(named: "back"), style: .done, target: self, action: #selector(didTappedBackButton)),
이미지 리소스 이름이 잘못되었습니다. `Back`으로 처리하셔야 보입니다.
```suggestion
      UIBarButtonItem(image: UIImage(named: "Back"), style: .done, target: self, action: #selector(didTappedBackButton)),
```

2023-02-17 08:25 UTC, WhiteHyun commented
추가로, Bookmark로 진입하는 것 뿐 아니라 다른 탭으로 진입할 시 Navigation의 left swipe가 먹히지 않습니다. 이건 왜 그런건지 혹시 얘기해주실 수 있나요?

2023-02-17 14:10 UTC, dlrjswns commented
<img width="366" alt="스크린샷 2023-02-17 오후 11 09 22" src="https://user-images.githubusercontent.com/39263235/219677767-7665b2db-2a9d-427b-ac80-23badcc209b8.png">
일단 맨 위에 테스트해보면 UI오류난다고 하셨는데 어떤 부분에서 오류가 나신건지 정확히 설명가능할까요 ?? 
지금 바로 해봤는데 문제가 없어서요 !!🧐🧐🧐

2023-02-17 14:11 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/BookmarkViewModel.swift
> +    }
넵 상관없습니다 !! 저희 어차피 에러처리에 대한 description만 내려주기로 해서 싸그리 merge로 묶어서 VC로 보내려고 합니다 !!

2023-02-17 14:11 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/BookmarkViewModel.swift
> +    }
허나 승현님 의견수용해서 에러에 대한 처리를 위해서 TODO로 주석처리해놓겠습니다 ☺️☺️👍

2023-02-17 14:13 UTC, dlrjswns commented on PLUB/Sources/Models/Recruitment/Response/BookmarkAllResponse.swift
> +  let views: Int
저도 궁금한 부분이긴한데 슬랙에 질문사항올려놨습니다 😁😁

2023-02-17 14:17 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/BookmarkViewModel.swift
> +        + "(data.time)"))
<img width="309" alt="스크린샷 2023-02-17 오후 11 15 53" src="https://user-images.githubusercontent.com/39263235/219679248-02afebf2-e85d-48ed-929a-5194b249e8cb.png">
1. 저희 아직 days값이 영어로 내려오는데 혹시 한글로 응답하신다는게 어떤 부분인지 여쭤봐도될까요 🧐🧐🧐??
2. 아 저 부분은 추후에 해당 셀 UI에 필요한 "13:00"와 같은 time값을 파싱하는 함수가 필요한데 아직 미구현상태라서 저렇게 두었습니다 !!

2023-02-17 14:20 UTC, dlrjswns commented on PLUB/Sources/Views/Home/BookmarkViewController.swift
> +class BookmarkHeaderView: UIView {
아 지금 확인해보니 변형되는 UI라서 final을 붙이지않았는데 토글버튼말고 헤더뷰에는 final을 붙여도 동작하네요 !! 수정하도록 하겠습니다 ☺️☺️👍

2023-02-17 14:20 UTC, dlrjswns commented on PLUB/Sources/Views/Home/BookmarkViewController.swift
> +}
헐 처음 보는 함수인데 바로 수정해보도록 하겠습니다, 바로 공부해봐야겠네요 감사합니다 승현님 👍👍👍

2023-02-17 14:25 UTC, dlrjswns commented on PLUB/Sources/Models/Recruitment/Response/BookmarkAllResponse.swift
> +}
음 북마크에 대한 오류는 응답값으로 북마크 성공 실패 여부를 Bool값으로 내려받고있구요 !! 

Decodable 모델에 해당 init을 작성한 이유는 말씀하시는 이유가 맞습니다만 UI를 건드는 모델 부분은 빈 배열을 받기에 상관없을것으로 보이고 request에러가 아니라 디코딩에러를 방지하고자 작성한 부분이라서 저렇게 구현하였습니다 !!

또한 서버통신작업에서 result값이 failure도 뜹니다 !! 그 이유는 해당 모델은 data관련 모델이고 따로 상태코드나 result값을 처리해주고있어서입니다 ✔️✔️✔️

2023-02-17 14:27 UTC, dlrjswns commented on PLUB/Sources/Views/Home/BookmarkViewController.swift
> +      UIBarButtonItem(image: UIImage(named: "back"), style: .done, target: self, action: #selector(didTappedBackButton)),
<img width="306" alt="스크린샷 2023-02-17 오후 11 26 31" src="https://user-images.githubusercontent.com/39263235/219681574-6d22bea9-613a-457a-aa8b-99f651d16e53.png">
엇 지금 제 xcode상으로는 back이 맞는거같은데 혹시 제 에셋이 최신화가 안되있는걸까요 ??

2023-02-17 14:29 UTC, dlrjswns commented
Q. 추가로, Bookmark로 진입하는 것 뿐 아니라 다른 탭으로 진입할 시 Navigation의 left swipe가 먹히지 않습니다. 이건 왜 그런건지 혹시 얘기해주실 수 있나요?

A. 다른 탭으로 진입한다는게 코어탭으로 진입 시 말씀하시는걸까요 ?? 만약에 맞다면 해당 부분은 따로 네비게이션바를 건든적이 없어서인데 이 부분 추가하면 좋을까요 ???

2023-02-17 15:14 UTC, soobin-k approved these changes
고생많으셨습니다 건준님!

2023-02-17 15:54 UTC, dlrjswns commented on PLUB/Sources/Models/Recruitment/Response/BookmarkAllResponse.swift
> +}
이 부분을 쭉 확인해보니까 승현님이 말씀하신대로 해당 값을 서버를 통해 받지않아도 무조건 값이 받아지니까 해당 에러를 찾기 쉽지않을꺼같네요 !! 제가 일단은 서버쪽에서 물어봐서 필수로 내려오는 값을 확인해서 한번 수정해보도록 할게요 ☺️☺️☺️

2023-02-18 00:16 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/BookmarkViewController.swift
> +      UIBarButtonItem(image: UIImage(named: "back"), style: .done, target: self, action: #selector(didTappedBackButton)),
저는 건준님 pr 그대로 가져다가 테스트를 해본 것 뿐인데 서로 다르게 보이네요.. 흠 이상하네요.

![image](https://user-images.githubusercontent.com/57972338/219819921-e0a4a84f-9722-4b46-9c13-135e547ecafa.png)

2023-02-18 00:22 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/BookmarkViewModel.swift
> +        + "(data.time)"))
아래 사진을 클릭해서 확대해보시면, 이미 한글로 받아져오기 때문에 map처리하면서 빈 문자열 값으로 세팅됩니다.

![image](https://user-images.githubusercontent.com/57972338/219820277-a83525e6-76de-4b86-958d-baf17e608b77.png)

아래는 `내 북마크 전체 조회` api 설명본입니다.
![image](https://user-images.githubusercontent.com/57972338/219820289-d030c09e-fbf9-482a-930c-ef08f5f59677.png)

2023-02-18 00:28 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/BookmarkViewController.swift
> +class BookmarkHeaderView: UIView {
final을 적용한 클래스는 앞으로 재정의하지 않을 것이라고 명시해두는 키워드라고 생각하시면 됩니다. 자세한 내용은 아래 링크를 참고해주세요.

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/inheritance/#Preventing-Overrides

2023-02-18 02:10 UTC, WhiteHyun commented
원래 swipe gesture로 알아서 view controller가 자동으로 pop되지 않나요?
최근에 navigation을 수정해서 그런지 gesture가 안 먹히네요

2023-02-18 07:51 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/BookmarkViewModel.swift
> +        + "(data.time)"))
엇 근데 저 부분 안드로이드쪽이랑 이야기해서 days값 영어로 통일하기로 했던거같은데 잠시만요 한번 여쭤보도록 하겠습니다 !!

2023-02-18 07:52 UTC, dlrjswns commented on PLUB/Sources/Views/Home/BookmarkViewController.swift
> +      UIBarButtonItem(image: UIImage(named: "back"), style: .done, target: self, action: #selector(didTappedBackButton)),
일단 해당 이미지 삭제 이후 다시 재삽입해놓고 pr올렸습니다 👍👍

2023-02-18 08:07 UTC, WhiteHyun approved these changes

2023-02-18 08:08 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/BookmarkViewModel.swift
> +        + "(data.time)"))
해당 부분 성흥님께 요청드려서 days는 영어로 통일되게 내려오도록 했습니다 !! 좋은 코멘트 감사드립니다 ☺️☺️☺️

2023-02-18 11:59 UTC, merged