[REFACTOR] 모델 리팩토링
PLUB2022/PLUB-iOS pull request #259
Opened 2023-04-05 16:17 UTC by dlrjswns

## 📌 PR 요약

🌱 작업한 내용
- SelectedCategoryCollectionViewCellModel을 위한 초기화함수를 추가

🌱 PR 포인트
- 뷰 모델에서 SelectedCategoryCollectionViewCellModel을 위한 로직을 축약하기위해 초기화함수를 만들어보았습니다 
- 현재 SelectedCategoryCollectionViewCellModel을 위한 초기화함수에서 내부 로직은 똑같은데 타입만 다른데 이걸 축약할 수 있는 방법이 있을까요 ??

``` swift
struct SelectedCategoryCollectionViewCellModel { 
  let plubbingID: Int
  let name: String
  let title: String
  let mainImage: String?
  let introduce: String
  var isBookmarked: Bool
  let selectedCategoryInfoModel: CategoryInfoListModel
  
  init(content: Content) {
    plubbingID = content.plubbingID
    name = content.name
    title = content.title
    mainImage = content.mainImage
    introduce = content.introduce
    isBookmarked = content.isBookmarked
    selectedCategoryInfoModel = .init(
      placeName: content.placeName,
      peopleCount: content.remainAccountNum,
      dateTime: content.days
      .map { $0.fromENGToKOR() }
      .joined(separator: ",")
    + " | "
    + "(data.time)")
  }
  
  init(content: BookmarkContent) {
    plubbingID = content.plubbingID
    name = content.name
    title = content.title
    mainImage = content.mainImage
    introduce = content.introduce
    isBookmarked = content.isBookmarked
    selectedCategoryInfoModel = .init(
      placeName: content.placeName,
      peopleCount: content.remainAccountNum,
      dateTime: content.days
      .map { $0.fromENGToKOR() }
      .joined(separator: ",")
    + " | "
    + "(data.time)")
  }
  
  init(content: SearchContent) {
    plubbingID = content.plubbingID
    name = content.name
    title = content.title
    mainImage = content.mainImage
    introduce = content.introduce
    isBookmarked = content.isBookmarked
    selectedCategoryInfoModel = .init(
      placeName: content.placeName,
      peopleCount: content.remainAccountNum,
      dateTime: content.days
      .map { $0.fromENGToKOR() }
      .joined(separator: ",")
    + " | "
    + "(data.time)")
  }
}
```
## 📮 관련 이슈
- Resolved: #258

2023-04-06 02:21 UTC, WhiteHyun reviewed
두 모델의 값이 전부 동일한데, 두 개를 하나로 합치면 해결되지 않을까요?
```swift
// MARK: - BookmarkContent

struct BookmarkContent: Codable {
  let plubbingID: Int
  let title: String
  let introduce: String
  let name: String
  let days: [String]
  let mainImage: String
  let address: String
  let roadAddress: String
  let placeName: String
  let placePositionX: Double
  let placePositionY: Double
  let remainAccountNum: Int
  let time: String
  let curAccountNum: Int
  let isBookmarked: Bool
  let views: Int
  
  enum CodingKeys: String, CodingKey {
    case plubbingID = "plubbingId"
    case title, introduce, name, days, mainImage, address, roadAddress, placeName, placePositionX, placePositionY, remainAccountNum, time, curAccountNum, isBookmarked, views
  }
}

// MARK: - SearchContent

struct SearchContent: Codable {
  let plubbingID: Int
  let title: String
  let introduce: String
  let name: String
  let days: [String]
  let mainImage: String
  let address: String
  let roadAddress: String
  let placeName: String
  let placePositionX: Double
  let placePositionY: Double
  let remainAccountNum: Int
  let time: String
  let curAccountNum: Int
  let isBookmarked: Bool
  let views: Int
  
  enum CodingKeys: String, CodingKey {
    case plubbingID = "plubbingId"
    case title, introduce, name, days, mainImage, address, roadAddress, placeName, placePositionX, placePositionY, remainAccountNum, time, curAccountNum, isBookmarked, views
  }
}
```

2023-04-06 04:33 UTC, dlrjswns commented
오오 좋은데요 ?? 바로 수정하도록 할게요 👍👍

2023-04-06 05:37 UTC, WhiteHyun requested changes

2023-04-06 05:37 UTC, WhiteHyun commented on PLUB/Sources/Models/Recruitment/Response/BookmarkAllResponse.swift
> +struct BoardContent: Codable {
메인페이지 쪽에서 게시글 관련 모델을 `Board`로 정의하고 있어 `BoardContent`라는 이름은 지양하는 것이 좋을 것 같습니다.
같은 단어지만 다른 의미가 되어버리니까요.
기존 BookmarkContent로 사용하셔도 좋을 것 같습니다.

2023-04-06 06:06 UTC, dlrjswns commented on PLUB/Sources/Models/Recruitment/Response/BookmarkAllResponse.swift
> +struct BoardContent: Codable {
엇 근데 위에 SearchContent와 BookmarkContent가 동일하니 통일하면 좋겠다는 의견을 내주셔서 가장 근접한 이름이라 생각했는데 그냥 BookmarkContent로 통일하는게 좋을까요 ??

2023-04-07 09:27 UTC, WhiteHyun approved these changes
고생하셨습니다!

2023-04-07 14:04 UTC, merged