[CHORE] 응답모델과 UI에 사용될 모델 따로 처리
PLUB2022/PLUB-iOS pull request #260
Opened 2023-04-06 05:14 UTC by dlrjswns

## 📌 PR 요약

🌱 작업한 내용
- 기존에 API를 통해 받아온 Category, SubCategory를 그대로 받아서 UI에 썼었는데 응답모델과 UI모델을 따로 두는게 어떻냐는 승현님의 의견이 있었습니다
* Category -> CategoryModel
* SubCategory -> SubCategoryStatus 
위처럼 이름을 변경하여 처리하도록 하였습니다

``` swift
struct CategoryModel {
  let id: Int
  let name: String
  let icon: String
  var subCategories: [SubCategoryStatus]
  
  init(category: Category) {
    id = category.id
    name = category.name
    icon = category.icon
    subCategories = category.subCategories.map { SubCategoryStatus(subCategory: $0) }
  }
}

struct SubCategoryStatus {
  let id: Int
  let name: String
  let categoryName: String
  let parentId: String
  var isSelected: Bool
  
  init(subCategory: SubCategory) {
    id = subCategory.id
    name = subCategory.name
    categoryName = subCategory.categoryName
    parentId = subCategory.parentId
    isSelected = false
  }
}
```

🌱 PR 포인트
- 제 화면뿐만 아니라 수빈님꺼랑 승현님이 작성한 코드에도 수정사항이 있으니 잘 확인해보시고 개발하신 기능 잘 동작하는지 확인해주시고 PR남겨주세요 👍👍

## 📮 관련 이슈
- Resolved: #257

2023-04-06 05:46 UTC, WhiteHyun requested changes

2023-04-06 05:46 UTC, WhiteHyun commented on PLUB/Sources/Models/Category/Response/AllCategoryListResponse.swift
> +}
모델과 프로퍼티의 `doc-comment`를 달면 좋을 것 같아요. 제가 작업한 것처럼요!

2023-04-06 05:46 UTC, WhiteHyun commented on PLUB/Sources/Models/Category/Response/AllCategoryListResponse.swift
>    }
1. 프로퍼티 doc-comment 작성해주시면 좋을 것 같습니다.
2. parentId -> parentID로 저희 컨벤션 지켜주시면 안될까요? 🥹 이렇게 빌겠습니다...

2023-04-06 05:46 UTC, WhiteHyun commented on PLUB/Sources/Models/Category/Response/AllCategoryListResponse.swift
> +  let id: Int
이 사이에도 구분을 위한 주석이 들어가면 훨 좋을 거 같아요.

```swift
// 대충 서버 응답 API 모델...
}

// MARK: - DTO

struct CategoryModel {
  let id: Int
  // ...
}
```

2023-04-06 06:03 UTC, dlrjswns commented on PLUB/Sources/Models/Category/Response/AllCategoryListResponse.swift
>    }
수정하겠습니다 :)

2023-04-06 06:04 UTC, dlrjswns commented on PLUB/Sources/Models/Category/Response/AllCategoryListResponse.swift
> +  let id: Int
이 부분은 최신 커밋확인하시면 CategoryModel은 파일이 이동한 상태입니다 확인해주세요 !!

2023-04-06 06:04 UTC, dlrjswns commented on PLUB/Sources/Models/Category/Response/AllCategoryListResponse.swift
> +}
넵 참고해서 작업해보도록 할게요 !!

2023-04-06 07:52 UTC, WhiteHyun requested changes

2023-04-06 07:52 UTC, WhiteHyun commented on PLUB/Sources/Models/Category/Response/AllCategoryListResponse.swift
>    }
혹시 무엇이 문제인지 생각해보셨나요?

2023-04-06 07:52 UTC, WhiteHyun commented on PLUB/Sources/Models/Category/Response/AllCategoryListResponse.swift
> +    parentID = try values.decodeIfPresent(String.self, forKey: .parentID) ?? ""
디코딩 기본값에 대해 Slack 확인 좀 부탁드립니다.

2023-04-06 07:52 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/Cell/RegisterInterest/InterestTypeCollectionViewCell.swift
> +  public func configureUI(with model: SubCategoryStatus) {
저희 public 안쓰기로 했습니다.

2023-04-06 13:18 UTC, dlrjswns commented on PLUB/Sources/Models/Category/Response/AllCategoryListResponse.swift
> +    parentID = try values.decodeIfPresent(String.self, forKey: .parentID) ?? ""
넵 확인했습니다 !!

2023-04-07 09:25 UTC, WhiteHyun requested changes

2023-04-07 09:25 UTC, WhiteHyun commented on PLUB/Sources/Models/Category/Response/AllCategoryListResponse.swift
>    }
저희 백엔드 API에 들어가보시면, parentId로 값이 들어오며, String으로 처리되어있습니다. 이 점 유의하여 수정해주시면 되겠습니다 :)

2023-04-08 05:40 UTC, WhiteHyun approved these changes
고생하셨습니다!!

2023-04-08 10:38 UTC, merged