[FIX] 필터화면로직수정
PLUB2022/PLUB-iOS pull request #279
Opened 2023-04-12 17:03 UTC by dlrjswns

## 📌 PR 요약

🌱 작업한 내용
- 요일무관 혹은 전체 선택/미선택 시 보이는 화면 UI 수정
- 요일무관 혹은 전체 선택/미선택 시 변하는 로직 수정
- 필터 Confirm버튼 선택 시 올바르지않는 Request 수정

🌱 PR 포인트
- 서브카테고리 조회를 통해 [전체]에 대한 카테고리를 내려받을 수 없어 따로 추가해주었습니다 
- 화면이 다시 보일때 데이터를 최신화시키는 트리거가 필요하지않을꺼같다는 판단에 init으로 categoryID를 받도록 하였습니다 
- categoryID를 String으로 받고있는데 Int로 변경하려니까 수정할게 너무 많아 나중에 따로 pr올리도록 하겠습니다

## 📸 동작영상
https://user-images.githubusercontent.com/39263235/231529941-e0e593c9-930a-4046-99ee-159060d84603.mp4

## 📮 관련 이슈
- Resolved: #254

2023-04-13 04:11 UTC, WhiteHyun requested changes

2023-04-13 04:11 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
> +            confirmDay.accept(confirmList)
최신 develop에서는 eng 프로퍼티가 존재하지 않아요! develop 브랜치를 가져온 뒤에 작업 후 다시 PR 리뷰 요청해주시겠나요?

2023-04-13 05:17 UTC, WhiteHyun requested changes
이번 주에 해당 ViewModel 리팩토링 가시죠~ 고고 :)

2023-04-13 05:17 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
> +            confirmList.append(subCategoryID)
중복된 코드가 많고 복잡해요. 코드를 줄일 수 있을 것 같아요.
예를 들어, 카테고리를 선택을 처리할 때 아래처럼 간략하게 만들 수 있어요.
```swift
let index = fetchList.firstIndex(where: { $0.subCategoryID == subCategoryID })!
fetchList[index].isTapped = isSelected

if subCategoryID == Constants.entireID { // 선택한 카테고리가 [전체]인 경우
  for i in 1..<fetchList.count {
    fetchList[i].isTapped = false
  }
  confirmList = []
}
else { // 선택한 카테고리가 세부카테고리 종류인 경우
  fetchList[0].isTapped = false
  if isSelected {
    confirmList.append(subCategoryID)
  }
  else {
    confirmList.removeAll { $0 == subCategoryID }
  }
}
selectingSubCategories.accept(fetchList)
confirmSubCategory.accept(confirmList)
```

아래 요일 쪽 파이프라인도 위 코드를 참고해서 리팩토링해보셨으면 좋겠습니다.

2023-04-13 05:17 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
>      }
하나의 프로퍼티만을 처리한다면, KeyPath를 활용해보세요!
```suggestion
    { subCategories, days in
      return subCategories.filter(\.isTapped).count > 0 && days.filter(\.isTapped).count > 0
    }
```

2023-04-13 05:17 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
> +    static let entireName = "제목"
이름이 잘못 되었어요.
```suggestion
    static let entireName = "전체"
```

2023-04-13 07:27 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
>      }
오 뭐야 이거 한번 사용해보도록 하겠습니다 감사합니다 👍

2023-04-13 07:28 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
> +            confirmDay.accept(confirmList)
아 저런 PR도 있었군요 ㅋㅋㅋㅋㅋ 한번 수정해보도록 하겠습니다 👍

2023-04-13 07:29 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
> +            confirmList.append(subCategoryID)
중복코드인지하고있긴했는데 한번 수정해봐야겠군요 🧐🧐🧐

2023-04-13 07:29 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
> +    static let entireName = "제목"
수정하도록 하겠습니다 ✔️✔️

2023-04-13 07:30 UTC, dlrjswns commented
> 이번 주에 해당 ViewModel 리팩토링 가시죠~ 고고 :)

저 소름돋았던게 저거 완성시키고나서 제가 봐도 길어서 승현님이 리팩토링하라할꺼같았는데 ㅋㅋㅋㅋㅋㅋㅋ 한번 이 부분을 제가 볼때는 기존에 승현님이 말씀해주셨던 함수활용하면 좋을꺼같아요, 한번 수정한거 보고 다시 의견내주세에ㅛ 👍👍

2023-04-14 09:02 UTC, WhiteHyun requested changes
필터를 적용한 뒤 다시 필터화면으로 들어갔을 때, 적용해뒀던 옵션이 초기화된 것 처럼 보입니다. 이 부분은 나중에 구현할 예정이신가요?

2023-04-14 09:02 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
> +      return subCategories.filter(\.isTapped).count > 0 && days.filter(\.isTapped).count > 0
### P3. 의견(고려해주세요)

리턴 타입은 명시하지 않아도 될 것 같아요.
```suggestion
    { subCategories, days in
      return subCategories.filter(\.isTapped).count > 0 && days.filter(\.isTapped).count > 0
```

2023-04-14 09:02 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
> +          }
### P4. 단순 의견(적용 안해도 무방해요)
entireID는 맨 첫 번째 element임을 보장하므로 아래처럼 해도 괜찮을 듯 싶습니다.

```suggestion
          fetchList[0].isTapped = false
```

2023-04-14 09:02 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
> +          }
### P4. 단순 의견(적용 안해도 무방해요)

day를 비교하는 if문이 이중으로 들어가있어서, map 대신에 for문으로 접근해서 값을 변경하는 것도 좋을 듯 싶어요.

```suggestion
        if day == .all { // [요일무관] 선택/미선택 했을 때, 나머키 요일 초기화
          for i in 1..<fetchList.count {
            fetchList[i].isTapped = false
          }
```

2023-04-14 09:02 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/Cell/Filter/RecruitmentFilterDateCollectionViewCell.swift
> +  }
### P1. 적극 반영해주세요
<img width="305" alt="image" src="https://user-images.githubusercontent.com/57972338/231996958-d07c4a45-aa38-4444-8003-de295844320c.png">

현재 `월`, `화`, `수`로 축약되어있는데, `요일`을 붙여주셔야 합니다.
```suggestion
  func configureUI(with model: RecruitmentFilterDateCollectionViewCellModel) {
    dayLabel.text = "\(model.day.kor)요일"
    isTapped = model.isTapped
  }
```

2023-04-14 12:37 UTC, dlrjswns commented
> 필터를 적용한 뒤 다시 필터화면으로 들어갔을 때, 적용해뒀던 옵션이 초기화된 것 처럼 보입니다. 이 부분은 나중에 구현할 예정이신가요?

아 그 부분은 온정님하고 경석님이랑 애기해본 결과 초기화하는걸로 결론났습니다 !!

2023-04-14 14:29 UTC, WhiteHyun approved these changes
아래 사항에 대해 수정 후 머지하시면 될 것 같아요.
리팩토링까지 해주셨네요! 고생하셨습니다. 👍

---

### P.S.

FilterSlider 위에 보이는 `인원 XX명`에 대한 폰트도 수정하셔야할 것 같아요. 이 녀석은 스타일 처리만 하면 되는 거라 나중에 수정하셔도 됩니다 :)
<img width="408" alt="image" src="https://user-images.githubusercontent.com/57972338/232072860-b9a0e62a-acc1-4685-81bd-e3066935df7a.png">

2023-04-14 14:29 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/RecruitmentFilterViewController.swift
>    weak var delegate: RecruitmentFilterDelegate?
mark와 같은 주석은 한 줄 띄어 작성해주시겠나요? 저희가 컨벤션을 그렇게 정했어서요. ☺️
```suggestion
  // MARK: - Properties
  
  weak var delegate: RecruitmentFilterDelegate?
```

2023-04-14 14:29 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/RecruitmentFilterViewController.swift
> +  private var subCategories: [RecruitmentFilterCollectionViewCellModel] = [] { // 서브카테고리를 위한 데이터
위와 같습니다.
```suggestion
  // MARK: - UI Models
  
  private var subCategories: [RecruitmentFilterCollectionViewCellModel] = [] { // 서브카테고리를 위한 데이터
```

2023-04-14 14:29 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/RecruitmentFilterViewController.swift
>    private let titleLabel = UILabel().then {
위와 같습니다.
```suggestion
  // MARK: - UI Components
  
  private let titleLabel = UILabel().then {
```

2023-04-14 14:29 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/RecruitmentFilterViewController.swift
> +  init(viewModel: RecruitmentFilterViewModelType) {
위와 같습니다.
```suggestion
  // MARK: - Initialization
  
  init(viewModel: RecruitmentFilterViewModelType) {
```

2023-04-14 14:29 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/RecruitmentFilterViewController.swift
> +  override func bind() {
위와 같습니다.
```suggestion
  // MARK: - Configurations
  
  override func bind() {
```

2023-04-14 14:29 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/RecruitmentFilterViewController.swift
>    @objc private func didTappedBackButton() {
위와 같습니다.
```suggestion
  // MARK: - Selector Method
  
  @objc private func didTappedBackButton() {
```

2023-04-14 14:29 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/RecruitmentFilterViewController.swift
>  extension RecruitmentFilterViewController: UICollectionViewDelegate, UICollectionViewDataSource {
위와 같습니다.
```suggestion
// MARK: - UICollectionViewDelegate, UICollectionViewDataSource

extension RecruitmentFilterViewController: UICollectionViewDelegate, UICollectionViewDataSource {
```

2023-04-14 14:29 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/RecruitmentFilterViewController.swift
>  extension RecruitmentFilterViewController: UICollectionViewDelegateFlowLayout {
위와 같습니다.
```suggestion
// MARK: - UICollectionViewDelegateFlowLayout

extension RecruitmentFilterViewController: UICollectionViewDelegateFlowLayout {
```

2023-04-14 14:29 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/RecruitmentFilterViewModel.swift
> +extension RecruitmentFilterViewModel: RecruitmentFilterViewModelType {
위와 같습니다.
```suggestion
// MARK: - Input & Output

extension RecruitmentFilterViewModel: RecruitmentFilterViewModelType {
```

2023-04-15 06:43 UTC, merged