[FIX] 지원질문에 대한 오류 해결
PLUB2022/PLUB-iOS pull request #324
Opened 2023-04-27 15:35 UTC by dlrjswns

## 📌 PR 요약

🌱 작업한 내용
- questionID가 동일한 질문을 질문리스트에 추가되는 오류를 해결하였습니다
- 동일한 questionID를 가진 질문에 대한 정보를 가지지않기위해 ApplyAnswer에 ==함수를 정의하였습니다.

## 📸 수정된 코드
``` swift
struct ApplyAnswer: Codable, Equatable {
  
  /// 질문 고유 Identifier
  let questionID: Int
  
  /// 질문에 맞춰  작성한 응답값
  let answer: String
  
  enum CodingKeys: String, CodingKey {
    case questionID = "questionId"
    case answer
  }
  
  public static func ==(lhs: ApplyAnswer, rhs: ApplyAnswer) -> Bool{
    return lhs.questionID == rhs.questionID
  }
}
```

## 📮 관련 이슈
- Resolved: #306

2023-04-27 16:37 UTC, WhiteHyun requested changes

2023-04-27 16:37 UTC, WhiteHyun commented on PLUB/Sources/Models/Recruitment/Request/ApplyForRecruitmentRequest.swift
> +  public static func ==(lhs: ApplyAnswer, rhs: ApplyAnswer) -> Bool{
아래로 바꿔주세용
```suggestion
 static func ==(lhs: ApplyAnswer, rhs: ApplyAnswer) -> Bool {
```

2023-04-28 07:16 UTC, dlrjswns commented on PLUB/Sources/Models/Recruitment/Request/ApplyForRecruitmentRequest.swift
> +  public static func ==(lhs: ApplyAnswer, rhs: ApplyAnswer) -> Bool{
넵 수정해서 올렸습니다 :)

2023-04-28 08:04 UTC, WhiteHyun approved these changes

2023-04-29 10:22 UTC, merged