[]
PLUB2022/PLUB-iOS pull request #327
Opened 2023-04-28 18:01 UTC by soobin-k

## 📌 PR 요약

🌱 작업한 내용
- 

🌱 PR 포인트
-

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #이슈번호

2023-04-29 05:03 UTC, WhiteHyun requested changes
엄.. 저희가 서로 맞췄던 MVVM 컨벤션과 사뭇 다른 거 같아요. 다시 맞춰서 올려주실 수 있으신가요?

2023-04-29 05:03 UTC, WhiteHyun commented on PLUB/Assets.xcassets/MyPage/pointActived.imageset/pointActived.png
pointActivated 파일 다시 가져오셔야할 거 같아요. 사이즈가 타원형으로 되어있네요

2023-05-03 14:54 UTC, soobin-k commented on PLUB/Assets.xcassets/MyPage/pointActived.imageset/pointActived.png
흠 이거 피그마에서 타원형으로 되어있긴했는데 제가 일단 수정해서 다시 넣겠습니다!

2023-05-03 15:45 UTC, WhiteHyun commented on PLUB/Sources/Views/MyPage/Active/ActiveMeetingViewModel.swift
> +  }
저희가 컨벤션을 정의할 때, ViewModel의 input과 output은 protocol로 분리해서 처리하고, ViewController는 ViewModel을 갖고 있는 게 아니라 protocol을 의존하는 식으로 구현하자고 했었어요! 그렇게 수정 해주실 수 있나요?

2023-05-03 15:56 UTC, soobin-k commented on PLUB/Sources/Views/MyPage/Active/ActiveMeetingViewModel.swift
> +  }
input output을 나누는거까지는 이해했는데 protocol로 분리하는것도 정했었나요?? 지금까지 그렇게 안해왔어서요..!

2023-05-03 16:03 UTC, soobin-k commented on PLUB/Sources/Views/MyPage/Active/ActiveMeetingViewModel.swift
> +  }
우선 이번 pr은 UI 위주로 구현한 상태이니 승인해주시면 다음 pr에 적용해서 올리겠습니다!

2023-05-03 16:21 UTC, WhiteHyun approved these changes

2023-05-03 16:22 UTC, merged