[FEAT] 메인페이지 일부 API 연동
PLUB2022/PLUB-iOS pull request #340
Opened 2023-05-03 15:53 UTC by dlrjswns

## 📌 PR 요약

🌱 작업한 내용
- 메인페이지 날짜 및 투두에 대한 데이터 바인딩 코드 추가
- 오늘인지 아닌지에 따른 UI 수정
- 오늘에 관련된 투두중 내가 작성한 투두가 존재할 경우 상단에 위치

🌱 PR 포인트
- 투두리스트 목표텍스트에 대한 33자 글자 수 제한은 외부에서 받아와야해서 아직 추가하지못하였습니다
- 날짜, 투두 셀 모델에 대한 API를 제외하고는 따로 pr올리도록 하겠습니다

## 📮 관련 이슈
- Resolved: #333

2023-05-03 16:01 UTC, soobin-k approved these changes
고생많으셨습니다 건준님!

2023-05-03 16:20 UTC, WhiteHyun requested changes

2023-05-03 16:20 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/MainPage/Cell/TodoCollectionHeaderView.swift
> +    $0.sizeToFit()
여기서는 넣지 않아도 될 것 같아요.

2023-05-03 16:20 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/MainPage/Cell/TodoCollectionViewCell.swift
> +      $0.trailing.equalToSuperview().inset(7)
이거 8로 잡으시면 될 거 같아요. 디자인 오류가 있는 듯 합니다.

```suggestion
      $0.top.trailing.equalToSuperview().inset(8)
```

2023-05-03 16:20 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/MainPage/ViewModel/TodolistViewModel.swift
> +  }
저희 컨벤션 맞추지 않았나요..? 다시 회귀하셨네요

2023-05-04 04:35 UTC, dlrjswns commented on PLUB/Sources/Views/Home/MainPage/ViewModel/TodolistViewModel.swift
> +  }
어 저희 기존에 컨벤션이 여러개가 존재할 경우에 그렇게 하기로했어서 저렇게 하긴했는데 이번에 기천님이랑 애기하면서 수정사항이 생겨서 그때 변경해서 올리도록 하겠습니다 !!

2023-05-04 04:35 UTC, dlrjswns commented on PLUB/Sources/Views/Home/MainPage/Cell/TodoCollectionViewCell.swift
> +      $0.trailing.equalToSuperview().inset(7)
그니까요 저런 부분이 되게 많더라구요 수정하도록 하겠습니다 !!

2023-05-04 04:35 UTC, dlrjswns commented on PLUB/Sources/Views/Home/MainPage/Cell/TodoCollectionHeaderView.swift
> +    $0.sizeToFit()
아 그러네요 !! sizeToFit만 남겨두고 삭제하도록 하겠습니다 👍

2023-05-04 10:44 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/MainPage/ViewModel/TodolistViewModel.swift
> +  }
왜 항상 다르게 이해하시는건가요 ㅋㅋㅋㅋ 세상에

2023-05-04 11:45 UTC, WhiteHyun approved these changes

2023-05-04 11:45 UTC, WhiteHyun commented on PLUB/Sources/Models/Todolist/Response/InquireTodolistResponse.swift
> +  }
기본값 세팅해두면 decodingError가 발생하지 않아서, 나중에 값 파싱에 실패했을 때 알지 못할 수도 있어요..!

2023-05-04 11:45 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/MainPage/Cell/TodoCollectionHeaderView.swift
> +    $0.sizeToFit()
앗 제가 얘기한 건 `sizeToFit()`이었어요. 어차피 auto layout으로 맞출거니까요!

2023-05-04 13:39 UTC, dlrjswns commented on PLUB/Sources/Models/Todolist/Response/InquireTodolistResponse.swift
> +  }
흠 이 부분을 어떻게 하는게 좋을지 참 애매모호하네요, 기본값지정하는게 개발하기편해서 저렇게 하긴했는데

2023-05-04 13:41 UTC, merged

2023-05-05 06:17 UTC, WhiteHyun commented on PLUB/Sources/Models/Todolist/Response/InquireTodolistResponse.swift
> +  }
아니면 목업 데이터를 init()으로 하나 빼서 처리하시는 건 어떠세요?

그러면 개발도 편하고, 나중에 값 파싱 실패했을 때 로그에서도 확인 가능해요 :)