[FEAT] 메인페이지 모임타이틀 전달
PLUB2022/PLUB-iOS pull request #378
Opened 2023-05-15 13:02 UTC by dlrjswns

## 📌 PR 요약

🌱 작업한 내용
- 메인페이지, 투두플래너, 게시글생성 화면에 대한 모임타이틀 전달
- 메인페이지 플로팅버튼 피그마디자인에 따른 코드 수정
- 투두플래너에 대한 이름 수정

## 📮 관련 이슈
- Resolved: #375

2023-05-15 14:52 UTC, WhiteHyun requested changes
Conflict 수정하고 다시 요청 주세용

2023-05-16 10:14 UTC, WhiteHyun reviewed
타이틀 제공해야하는 곳이 아카이브에도 필요하고 공지쪽에도 필요해요. 추가로 구현해주실 수 있나요?

2023-05-16 12:40 UTC, dlrjswns commented
> 타이틀 제공해야하는 곳이 아카이브에도 필요하고 공지쪽에도 필요해요. 추가로 구현해주실 수 있나요?

아 그럼요 잠시만요 !!

2023-05-16 13:03 UTC, dlrjswns commented
승현님 일단 추가하긴했는데 이게 제가 지금 상유님이랑 헤더뷰없애는거 쇼부보고있어서 만약에 헤더뷰없애는거 허용되면은 다시 코드 변경하도록 할게요 !!

2023-05-17 03:55 UTC, WhiteHyun approved these changes

2023-05-17 10:11 UTC, merged