[FEAT] 투두인증모달 구현
PLUB2022/PLUB-iOS pull request #382
Opened 2023-05-17 14:47 UTC by dlrjswns

## 📌 PR 요약

🌱 작업한 내용
- 투두인증 성공 시에 따른 proofImage를 이용하여 모달 UI를 띄우는 코드를 작성하였습니다.

p.s @soobin-k 코드를 작성하던중에 라벨 간격함수를 사용할 일이 있어서 UILabel + Ex파일에 addLinespacing함수를 보던 와중에 굳이 라벨을 안받아와도 될꺼같아서 변경하긴했는데 혹시 기존 작업하던 부분이 안된다면 말해주시면 다시 되돌리도록 하겠습니다 ✔️

## 📮 관련 이슈
- Resolved: #377

2023-05-18 04:12 UTC, WhiteHyun requested changes
웬만한 UI 구성 하셨으면 영상 올려주시면 좋겠어요! 최대한 리뷰어 입장에 맞춰서 작성해주시면 감사하겠습니다.

---

지금 투두에서 UI 버그 났어요.

|Overlapping|Complete Image|
|:-:|:-:|
|![IMG_2111](https://github.com/PLUB2022/PLUB-iOS/assets/57972338/d1ca3d8b-93df-4cc3-b9ab-451fa8ec52fb)|![IMG_2112](https://github.com/PLUB2022/PLUB-iOS/assets/57972338/becaf1b4-0210-4397-9bb5-39b6c540d85c)|

첫 번째는 이미지 추가 라벨이랑 사진이 겹쳐보이고 있고,
두 번째는 `Lottie Animation`이 들어가야하는데 이미지가 보여요.

2023-05-18 04:32 UTC, dlrjswns commented
> UI 구성을 하셨다면 어떤 부분을 구현했는지 시연하는 영상을 올려주시면 좋겠어요! 최대한 리뷰어 입장에 맞춰서 작성해주시면 감사하겠습니다.
> 
> 지금 투두에서 UI 버그 났어요.
> 
> Overlapping	Complete Image
> ![IMG_2111](https://user-images.githubusercontent.com/57972338/239137124-d1ca3d8b-93df-4cc3-b9ab-451fa8ec52fb.PNG)	![IMG_2112](https://user-images.githubusercontent.com/57972338/239137137-becaf1b4-0210-4397-9bb5-39b6c540d85c.PNG)
> 첫 번째는 이미지 추가 라벨이랑 사진이 겹쳐보이고 있고, 두 번째는 `Lottie Animation`이 들어가야하는데 이미지가 보여요.

https://plubhq.slack.com/archives/C03SN0RUHLP/p1684322460498419
위 슬랙보시면은 투두인증성공시 받는 응답모델의 proofImage를 사용하면 된다고해서 저렇게 구현해두었습니다 !!

아 영상올리려했는데 계속 용량초과내서 저렇게 했는데 이후엔 캡처라도 해서 올리도록 하겠습니다 ✔️

2023-05-18 04:49 UTC, dlrjswns commented
<img width="349" alt="스크린샷 2023-05-18 오후 1 43 47" src="https://github.com/PLUB2022/PLUB-iOS/assets/39263235/b5d950b3-ca4f-4cb4-8cad-f2a60cc7db6f">
수정했습니다 !!

2023-05-18 12:42 UTC, WhiteHyun commented
> https://plubhq.slack.com/archives/C03SN0RUHLP/p1684322460498419 위 슬랙보시면은 투두인증성공시 받는 응답모델의 proofImage를 사용하면 된다고해서 저렇게 구현해두었습니다 !!
> 
> 아 영상올리려했는데 계속 용량초과내서 저렇게 했는데 이후엔 캡처라도 해서 올리도록 하겠습니다 ✔️

음.. Figma에서는 Lottie 이미지로 되어있는데, 서버에서는 인증 사진을 보내주니 어디가 맞는 지 모르겠네요 ㅋㅋㅋ
그러면 인증 완료 화면도 Figma 디자인 상에서 일반 사진으로 대체되어야할텐데 업데이트가 안된걸까요..? 🤨

2023-05-18 14:06 UTC, dlrjswns commented
> > https://plubhq.slack.com/archives/C03SN0RUHLP/p1684322460498419 위 슬랙보시면은 투두인증성공시 받는 응답모델의 proofImage를 사용하면 된다고해서 저렇게 구현해두었습니다 !!
> > 아 영상올리려했는데 계속 용량초과내서 저렇게 했는데 이후엔 캡처라도 해서 올리도록 하겠습니다 ✔️
> 
> 음.. Figma에서는 Lottie 이미지로 되어있는데, 서버에서는 인증 사진을 보내주니 어디가 맞는 지 모르겠네요 ㅋㅋㅋ 그러면 인증 완료 화면도 Figma 디자인 상에서 일반 사진으로 대체되어야할텐데 업데이트가 안된걸까요..? 🤨

흠 일단 저렇게 하긴했는데 저도 좀 헷갈려서 물어보고하긴한거거든요 🧐🧐

2023-05-19 14:21 UTC, WhiteHyun commented
기획에서는 애니메이션이 들어간다고 하네요!
Lottie로 수정해주세요!

2023-05-20 07:12 UTC, WhiteHyun requested changes
다음부터는 서버 뿐 아니라 기획과의 면밀한 소통으로 확실하게 구현해주셨으면 좋겠습니다! 아니면 저에게 따로 DM 보내주셔도 돼요. (안그러면 지금같이 다 구현해놓고 다시 알아보고 수정해야하는 불상사가 생기고, 커뮤니케이션 비용이 낭비되니까요. 😅)
아무튼 수정하시고 다시 요청보내시면 확인후 Approve 하겠습니다! 고생하셨어용

2023-05-20 18:50 UTC, WhiteHyun approved these changes
고생하셨습니다!

2023-05-21 04:35 UTC, merged