[FEAT] 메인페이지 게시글 바텀시트 기능 구현
PLUB2022/PLUB-iOS pull request #399
Opened 2023-06-05 07:57 UTC by dlrjswns

## 📌 PR 요약

🌱 작업한 내용
- 게시글 수정 기능 구현
- 게시글 삭제 기능 구현
- 게시글 고정 기능 구현
- 클립보드리스트 UI가 무한 쪼개어짐 현상 해결
- 작성자, 호스트 여부에 따른 바텀시트 동작
- BoardCollectionViewCell 부분 이미지 재사용에 따른 문제로 prepareForReuse부분 수정했습니다

🌱 PR 포인트
- 게시글 신고 API 없는거같아서 미구현
- 게시글 생성에 따른 데이터 최신화 미구현

## 📸 스크린샷
|게시글 삭제|
|:--:|
|https://github.com/PLUB2022/PLUB-iOS/assets/39263235/5b50618f-746a-4b90-a46e-f35268c24749|

|게시글 고정|
|:--:|
|https://github.com/PLUB2022/PLUB-iOS/assets/39263235/be2a8d3b-34c7-410d-b69c-78751a7ec70b|

|게시글 수정 텍스트 타입|
|:--:|
|https://github.com/PLUB2022/PLUB-iOS/assets/39263235/6d9cc52d-189e-4843-a26a-080d96aa21ae|

ps. 1. 포토타입 및 포토텍스트타입 영상이 최대한 짧게 찍으려 해도 양이 큰거 같아서 올리지못하였습니다, 참고해주세요 !!
      2. 게시글 생성하는 동작을 CreateBoardVC안에서 하다보니까 데이터최신화하는데 힘들더라구요, 해당 기능을 BoardVC로 이전하는 pr을 따로 올리도록 하겠습니다

## 📮 관련 이슈
- Resolved: #398

2023-06-05 09:03 UTC, WhiteHyun requested changes
음.. 게시글 수정 화면은 게시글 생성화면과 동일하잖아요?
그래서 뷰에 대한 코드는 그대로 두고 내부 기능으로 동작하는 로직만 수정하면 될 것 같아보여요.
지금 구현해주신 코드를 보면 CreateBoardViewController에 접근할 때 modify와 edit(게시글 작성용인데 왜 이름이 edit인지도 모르겠네요. post가 나을듯 합니다)에 따라서 코드를 분산시키고 있잖아요?
너무 하드코딩하신 것 같은데, 뷰모델을 추상화해서 게시글 생성과 수정을 동시에 작업하도록 하는 건 어떤가요?

Archive에서도 Board와 비슷한 기능을 가지고 있어요. 저는 Archive 생성과 수정에 대한 ViewController 코드는 그대로지만, ViewModel을 갈아끼우면서 기능을 다르게 사용하고 있어요. 제 코드가 정답은 아니지만, 도움이 될 수도 있기에 한 번 체크해보시는 것도 추천드립니다 ㅎ..

2023-06-05 14:35 UTC, dlrjswns commented
> 

지금 보니 edit보다는 post나 create가 훨씬 낫겠네요 !! 
그 제가 잘 이해를 못하는걸 수도 있는데 CreateBoardVC는 뷰를 건든 부분이 없는데 혹시 어떤걸 말씀하시는걸까요...?
CreateType을 넣은 이유는 수정하기전에 기존 데이터를 가져와야하는 문제때문에 한거라서 뷰모델을 통해서 가져오는게 아니고 아마 말씀하시는게 BoardVC때문인거라면 그 부분은 이후에 수정하려합니다 !! 고쳐야할 부분이 많아질꺼같아서요 😀😀

이게 처음에 게시글수정을 저런식으로 수정할지 몰라서 CreateBoardVC에서 게시글생성하는 로직을 뷰모델에 넣었던건데 좀 복잡하게 된거같긴하네요, 말씀하신 부분을 BoardVC의 뷰모델에서 처리할 수 있게끔 수정이 필요할꺼같습니다 😭😭

2023-06-06 06:21 UTC, WhiteHyun approved these changes
> 그 제가 잘 이해를 못하는걸 수도 있는데 CreateBoardVC는 뷰를 건든 부분이 없는데 혹시 어떤걸 말씀하시는걸까요...?

제가 말씀드리고자 한 거는, 보여지는 View는 동일하기에 **ViewController에서 코드를 추가하거나 변경할 필요가 없다.** 라는 의미었어요. 제가 ViewController를 View라고 표현한 것에 대해 오해가 생겼네요.

---

>  CreateType을 넣은 이유는 수정하기전에 기존 데이터를 가져와야하는 문제때문에 한거라서 뷰모델을 통해서 가져오는게 아니고...

넵 알고있습니다. ViewController에서 `수정!`이라는 enum type이 들어오면 수정해야할 기존의 Context(문구 또는 이미지)를 띄워주어야하는 작업 때문에 그렇게 하신 것으로 보여요. 뿐만 아니라, Context를 ViewModel에게 전달하는 과정까지도요.

제가 여기서 얘기하고자 했던 것은 enum으로 코드를 분류하는 법 대신 **ViewModel의 추상화는 어떤지 권유드린 것**입니다.

언급했다시피 Archive 기능에서 이러한 방식이 채택되어있습니다.
`ArchiveUploadVC`는 아카이브 업로드와 아카이브 수정이라는 동일한 뷰로써 존재하지만, 추상화되어있는 `ArchiveUploadViewModel`에 따라 업로드 기능을 갖는 뷰가 될 수 있고, 수정 기능을 갖는 뷰가 될 수 있어요.

물론

# 코드에 정답은 없습니다.

단지 구현 방식에 차이만 있을 뿐이죠! 지금 계속 설계해오고 계신 방식이 있으신 것 같아보이고, CreateBoard에서 업로드랑 수정 말고 또 다른 기능이 들어갈 것 같아보이지는 않으니(만약 그렇다면 나중에 case를 더 추가해야하는 불상사가...) 다음 PR을 기대하도록 하겠습니다.. 하하

고생하셨습니다!

2023-06-06 08:07 UTC, soobin-k approved these changes
고생 많으셨습니다 건준님!

2023-06-06 08:07 UTC, soobin-k commented on PLUB/Sources/Views/Home/MainPage/CreateBoardViewController.swift
> +  case edit // 게시글 작성용
저도 승현님이랑 동일한 의견으로 게시글 생성이면 create or write으로 네이밍하면 더 좋을 것 같습니다!
CreateBoradViewController도 이름을 WriteBoardViewController라고 변경해봐도 좋을 것 같아요!

2023-06-06 11:07 UTC, dlrjswns commented
> > 그 제가 잘 이해를 못하는걸 수도 있는데 CreateBoardVC는 뷰를 건든 부분이 없는데 혹시 어떤걸 말씀하시는걸까요...?
> 
> 제가 말씀드리고자 한 거는, 보여지는 View는 동일하기에 **ViewController에서 코드를 추가하거나 변경할 필요가 없다.** 라는 의미었어요. 제가 ViewController를 View라고 표현한 것에 대해 오해가 생겼네요.
> 
> > CreateType을 넣은 이유는 수정하기전에 기존 데이터를 가져와야하는 문제때문에 한거라서 뷰모델을 통해서 가져오는게 아니고...
> 
> 넵 알고있습니다. ViewController에서 `수정!`이라는 enum type이 들어오면 수정해야할 기존의 Context(문구 또는 이미지)를 띄워주어야하는 작업 때문에 그렇게 하신 것으로 보여요. 뿐만 아니라, Context를 ViewModel에게 전달하는 과정까지도요.
> 
> 제가 여기서 얘기하고자 했던 것은 enum으로 코드를 분류하는 법 대신 **ViewModel의 추상화는 어떤지 권유드린 것**입니다.
> 
> 언급했다시피 Archive 기능에서 이러한 방식이 채택되어있습니다. `ArchiveUploadVC`는 아카이브 업로드와 아카이브 수정이라는 동일한 뷰로써 존재하지만, 추상화되어있는 `ArchiveUploadViewModel`에 따라 업로드 기능을 갖는 뷰가 될 수 있고, 수정 기능을 갖는 뷰가 될 수 있어요.
> 
> 물론
> 
> # 코드에 정답은 없습니다.
> 단지 구현 방식에 차이만 있을 뿐이죠! 지금 계속 설계해온 방식이 있으신 것 같아보이고, CreateBoard에서 업로드랑 수정 말고 또 다른 기능이 들어갈 것 같아보이지는 않으니(만약 그렇다면 나중에 case를 더 추가해야하는 불상사가...) 이 PR과 이어지는 다음 PR을 기대해보도록 하겠습니다.
> 
> 고생하셨습니다!

엇 알겠습니다 !! 저도 사실 좀 데이터를 가져오는 로직이 난잡하다라는 생각은 들고있어서 BoardVC로 해당 로직을 옮기는 과정에서 Archive를 참고하여 수정해보도록 하겠습니다 !! 
항상 승현님 좋은 의견감사드리고 다음 pr보시고 개선사항이 필요할것같다싶으면 편하게 말씀해주세요 !!

2023-06-06 11:08 UTC, dlrjswns commented on PLUB/Sources/Views/Home/MainPage/CreateBoardViewController.swift
> +  case edit // 게시글 작성용
네 알겠습니다 !! 수정하도록 하겠습니다

2023-06-12 12:45 UTC, merged