Feat/80 recruitment/UI
PLUB2022/PLUB-iOS pull request #88
Opened 2023-01-23 15:17 UTC by dlrjswns

## 📌 PR 요약

🌱 작업한 내용
- API 연동을 위한 홈 / 모집 관련 뷰 모델 및 모델 수정

🌱 PR 포인트
- 지원질문화면은 아직 어떻게 화면에 들어가는지 몰라 미작업 
- 모집글에 대한 세부화면 중 participantListInfoView에 대한 UI 수정해야함

## 📮 관련 이슈
- Resolved: #80

2023-01-23 15:51 UTC, WhiteHyun requested changes

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/Model/Recruitment/DetailRecruitmentResponse.swift
> +  }
이걸 구현하신 이유가 파싱이 잘못되었을 때 죽는 현상을 방지하기 위함인가요?

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/Model/Recruitment/DetailRecruitmentModel.swift
> +}
네트워크 모델과는 동일하지만 역할을 분리하고자 모델을 추가로 만드신건가요?

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/IntroduceCategoryViewModel.swift
> +      .disposed(by: disposeBag)
뭔가 다음과 같이 줄일 수 있을 것 같긴한데 굳이? 싶긴 하네요 ㅎㅎ

```swift
selectingPlubbingId
  .flatMapLatest(RecruitmentService.shared.inquireDetailRecruitment(plubbingId:))
  .compactMap { result -> DetailRecruitmentResponse? in
    guard case .success(let detailRecruitmentResponse) = result else { return nil }
    return detailRecruitmentResponse.data
  }
  .map { $0. map {  DetailRecruitmentModel(response: $0) } }
  .bind(to: fetchingDetailRecruitment)
  .disposed(by: disposeBag)
```

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/IntroduceCategoryViewModel.swift
> +    let fetchingDetail = selectingPlubbingId
selectingPlubbingId를 `selectingPlubbingID`로 바꿔주세요!

https://github.com/StyleShare/swift-style-guide#%EC%95%BD%EC%96%B4

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/SelectedCategoryViewModel.swift
> +  let selectCategoryId: AnyObserver<String>
`selectCategoryID`로 바꿔주세요!

https://github.com/StyleShare/swift-style-guide#%EC%95%BD%EC%96%B4

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/SelectedCategoryViewModel.swift
> +    let selectingCategoryId = PublishSubject<String>()
이하 동문입니다.

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/SelectedCategoryViewModel.swift
> +    self.selectCategoryId = selectingCategoryId.asObserver()
이하 동문입니다.

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/SelectedCategoryViewModel.swift
> +    }
이건 compactMap으로 줄일 수 있지 않나요?
```suggestion
    let selectingContents = successFetching.compactMap { $0?.content }
```
이렇게요!

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/DetailRecruitmentViewModel.swift
> +      .share()
share()를 하는 이유는 뭔가요?

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/Model/Recruitment/RecruitmentQuestionResponse.swift
> +  }
위와 같습니다.

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/DetailRecruitmentViewController.swift
> +  private let plubbingId: Int
`plubbingID`로 변경해주세요!

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/Component/ParticipantListView.swift
> +    }
make 제거해주세요!

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/Component/ParticipantListView.swift
> +//  }
필요없는 코드라면 제거해주세요 :(

2023-01-23 15:51 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/Component/ParticipantListView.swift
> +  ]).then {
되도록 subviews 할당하는 것은 한 곳에 몰아서 해주세요. configureUI에서 작업하셨던데 거기에 빼는 게 좀 더 가독성에 좋을 것 같아요 :)

2023-01-23 15:56 UTC, dlrjswns commented on PLUB/Sources/Views/Home/Model/Recruitment/DetailRecruitmentResponse.swift
> +  }
넵 맞습니다 :) 아직 정확히 어떤 값이 필수적인 요소인지 확실치 되지않았고 decode시에 런타임크래시를 방지하기위함입니다

2023-01-23 15:56 UTC, dlrjswns commented on PLUB/Sources/Views/Home/Model/Recruitment/DetailRecruitmentModel.swift
> +}
동일하지만 응답값의 일부만을 사용하기에 따로 만들어두었습니다 👍👍

2023-01-23 15:56 UTC, dlrjswns commented on PLUB/Sources/Views/Home/Model/Recruitment/DetailRecruitmentModel.swift
> +}
추후에 서버에서 내려주는 데이터와는 다른 데이터로 파싱을 하기위함이기도 합니다

2023-01-23 15:57 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/IntroduceCategoryViewModel.swift
> +      .disposed(by: disposeBag)
이 부분은 사실 기존 줄이는 코드를 사용했었으나 xcode오류인지 계속 오류가 나서 그냥 하나하나 작성하여 코드하였습니다 !!

2023-01-23 15:58 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/IntroduceCategoryViewModel.swift
> +    let fetchingDetail = selectingPlubbingId
아 이 부분은 서버쪽에서 plubbindId, categoryId 이렇게 내려줘서 그것에 네이밍을 맞추긴했는데 변경할까요 ??

2023-01-23 15:58 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/SelectedCategoryViewModel.swift
> +  let selectCategoryId: AnyObserver<String>
이 부분도 앞에 말한 부분과 동일합니다 !!

2023-01-23 15:59 UTC, dlrjswns commented on PLUB/Sources/Views/Home/Component/ParticipantListView.swift
> +//  }
아 이 부분 변경중이라 잊고있었는데 제거해야겠네요 감사합니다 👍👍!!

2023-01-23 16:00 UTC, dlrjswns commented on PLUB/Sources/Views/Home/Component/ParticipantListView.swift
> +  ]).then {
아 이 부분 또한 아직 변경중인 부분이라서 테스트중이였는데 잊고있었네요 👀👀👀 이 부분 다음에 다시 손봐야될꺼같아요 👍👍

2023-01-23 16:31 UTC, WhiteHyun commented on PLUB/Sources/Views/Home/ViewModel/IntroduceCategoryViewModel.swift
> +    let fetchingDetail = selectingPlubbingId
약어는 StyleShare에 맞게 변경해주세요, 저희가 커스텀 컨벤션으로 정한 것 이외에는 StyleShare에 맞춰 가는 게 좋을 것 같아요.

2023-01-24 23:01 UTC, WhiteHyun reviewed
위 질문 사항들에 대해서 답변 해 주세요!

2023-01-25 04:00 UTC, soobin-k commented
고생많으셨습니다 건준님!👍

2023-01-25 04:00 UTC, soobin-k approved these changes

2023-01-25 08:09 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/SelectedCategoryViewModel.swift
> +    }
엇 넵 맞습니다 !! compactMap으로  하면 좀 더 깔끔하게 할 수 있겠네요 !!

2023-01-25 08:10 UTC, dlrjswns commented on PLUB/Sources/Views/Home/ViewModel/DetailRecruitmentViewModel.swift
> +      .share()
저희가 error에 해당하는 분기처리가 여러개인데 구독하여 뿌려줄때마다 새로운 Observable을 생성하므로 share연산자를 사용해주었습니다 !!

2023-01-25 08:38 UTC, dlrjswns reviewed
코멘트남겼습니다 ☺️☺️

2023-01-25 08:47 UTC, WhiteHyun approved these changes

2023-01-25 09:07 UTC, merged